### ISSUE TITLE
Unable to Launch specific app using this approach

### ISSUE THREAD

**Issue by Naresh-Edla** [soygul/electron-chromedriver#6]
I need to automate "Vysor" electron app using the python selenium
git clone https://github.com/koush/electron-chrome.git

**electron  ./electron_chrome --app-id=gidgenkbbabolejbgbpnhbimgjbffefm** will start Vysor app automatically by electron.

With python Selenium:
i changed run.py as follows
chromedriver_path = "./chromedriver"
electron_path = "./electron"

opts = Options()

opts.binary_location = electron_path
options.add_argument='./electron-chrome/'
options.add_argument='--app-id=gidgenkbbabolejbgbpnhbimgjbffefm'

driver = webdriver.Chrome(executable_path=chromedriver_path, chrome_options=opts)

Result: It's launching only electron and not launching  "Vysor" app.

**Comment by soygul** [comment]
I don't know how `add_argument` works. Might not be how you expect it to work. Check the docs.

Also this doesn't look like an issue with `electron-chromedriver` so closing this. You can try asking this question on Stackoverflow.
