### ISSUE TITLE
Failed to install v1.7.1 on Windows 7

### ISSUE THREAD

**Issue by Ribeiro** [soygul/electron-chromedriver#7]
Please, help me out on how to fix this install failure. Thanks! See npm-debug.log related part below:

87319 silly install electron-chromedriver@1.7.1 D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.staging\electron-chromedriver-f8fbee0b
87320 info lifecycle electron-chromedriver@1.7.1~install: electron-chromedriver@1.7.1
87321 verbose lifecycle electron-chromedriver@1.7.1~install: unsafe-perm in lifecycle true
87322 verbose lifecycle electron-chromedriver@1.7.1~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron-chromedriver\node_modules\.bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.bin;D:\Users\008188L1\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Users\008188L1\bin;C:\oracle\ora92\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\DMIX;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;D:\Users\008188L1\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
87323 verbose lifecycle electron-chromedriver@1.7.1~install: CWD: D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron-chromedriver
87324 silly lifecycle electron-chromedriver@1.7.1~install: Args: [ '/d /s /c', 'node ./download-chromedriver.js' ]
87325 silly lifecycle electron-chromedriver@1.7.1~install: Returned: code: 1  signal: null
87326 info lifecycle electron-chromedriver@1.7.1~install: Failed to exec install script
87327 verbose unlock done using D:\Users\008188L1\AppData\Roaming\npm-cache\_locks\staging-c221d9790d1cd1b7.lock for D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.staging
87328 silly rollbackFailedOptional Starting
87329 silly rollbackFailedOptional Finishing
87330 silly runTopLevelLifecycles Finishing
87331 silly install printInstalled
87332 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
87333 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
87334 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
87334 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87334 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87334 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87335 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.1.0 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
87336 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
87337 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
87337 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87337 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87337 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87338 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
87339 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
87340 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
87340 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
87340 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
87340 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
87341 warn ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
87342 verbose If you need help, you may report this error at:
87342 verbose     <https://github.com/npm/npm/issues>
87343 warn integrador@1.6.86 No repository field.
87344 verbose If you need help, you may report this error at:
87344 verbose     <https://github.com/npm/npm/issues>
87345 warn integrador@1.6.86 No license field.
87346 verbose If you need help, you may report this error at:
87346 verbose     <https://github.com/npm/npm/issues>
87347 verbose stack Error: electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
87347 verbose stack Exit status 1
87347 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
87347 verbose stack     at emitTwo (events.js:106:13)
87347 verbose stack     at EventEmitter.emit (events.js:191:7)
87347 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
87347 verbose stack     at emitTwo (events.js:106:13)
87347 verbose stack     at ChildProcess.emit (events.js:191:7)
87347 verbose stack     at maybeClose (internal/child_process.js:891:16)
87347 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
87348 verbose pkgid electron-chromedriver@1.7.1
87349 verbose cwd D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe
87350 error Windows_NT 6.1.7601
87351 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "--verbose"
87352 error node v6.11.1
87353 error npm  v3.10.10
87354 error code ELIFECYCLE
87355 error electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
87355 error Exit status 1
87356 error Failed at the electron-chromedriver@1.7.1 install script 'node ./download-chromedriver.js'.
87356 error Make sure you have the latest version of node.js and npm installed.
87356 error If you do, this is most likely a problem with the electron-chromedriver package,
87356 error not with npm itself.
87356 error Tell the author that this fails on your system:
87356 error     node ./download-chromedriver.js
87356 error You can get information on how to open an issue for this project with:
87356 error     npm bugs electron-chromedriver
87356 error Or if that isn't available, you can get their info via:
87356 error     npm owner ls electron-chromedriver
87356 error There is likely additional logging output above.
87357 verbose exit [ 1, true ]

**Comment by soygul** [comment]
Looks like a Windows or environment related issue. I can't help since I don't use Windows.

**Comment by Ribeiro** [comment]
@soygul Solved using CNTLM! =)
